
FROM debian:buster






ARG IMAGE_ARG_APT_MIRROR

ARG IMAGE_ARG_ENCODING
ARG IMAGE_ARG_JAVA_OPTS
ARG IMAGE_ARG_LANGUAGE
ARG IMAGE_ARG_LOCALE
ARG IMAGE_ARG_REGION
ARG IMAGE_ARG_TZ_AREA
ARG IMAGE_ARG_TZ_ZONE

ARG IMAGE_ARG_USER
ARG IMAGE_ARG_VERSION





ENV HOME /home/${IMAGE_ARG_USER:-debian}

ENV JAVA_OPTS -Duser.language=${IMAGE_ARG_LANGUAGE:-en} -Duser.region=${IMAGE_ARG_REGION:-US} -Dfile.encoding=${IMAGE_ARG_ENCODING:-UTF-8} -Duser.timezone=${IMAGE_ARG_TZ_AREA:-Etc}/${IMAGE_ARG_TZ_ZONE:-UTC} ${IMAGE_ARG_JAVA_OPTS}
# Do not set LANG or LC_ALL by ENV instruction under debian buster or you will get "/bin/bash: warning: setlocale: LC_ALL: cannot change locale"
#ENV LANG ${IMAGE_ARG_LOCALE:-en_US}.${IMAGE_ARG_ENCODING:-UTF-8}
#ENV LC_ALL ${IMAGE_ARG_LOCALE:-en_US}.${IMAGE_ARG_ENCODING:-UTF-8}


#COPY --from=cirepo/locale:%IMAGE_ARG_LOCALE%.%IMAGE_ARG_ENCODING%_%IMAGE_ARG_TZ_AREA%.%IMAGE_ARG_TZ_ZONE%-buster-archive /data/root /


# install netstat to allow connection health check with
# netstat -tan | grep ESTABLISHED
RUN set -ex \
  && echo "deb http://deb.debian.org/debian/ sid main" | tee -a /etc/apt/sources.list \
  && apt-get -y --allow-unauthenticated update \
  && apt-get -y install curl iputils-ping net-tools openjdk-8-jdk sudo \
  && apt-get -q -y autoremove \
  && apt-get -q -y clean && rm -rf /var/lib/apt/lists/* && rm -f /var/cache/apt/*.bin

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN set -ex \
  && curl --create-dirs -sSLo /usr/share/jenkins/swarm-client-${IMAGE_ARG_VERSION:-3.15}-jar-with-dependencies.jar \
    https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/${IMAGE_ARG_VERSION:-3.15}/swarm-client-${IMAGE_ARG_VERSION:-3.15}.jar \
  && chmod 755 /usr/share/jenkins \
  && mkdir -p /home/${IMAGE_ARG_USER:-debian}/.m2 \
  && mkdir -p /home/${IMAGE_ARG_USER:-debian}/.ssh

VOLUME /home/${IMAGE_ARG_USER:-debian}


RUN set -ex \
  && echo ===== Create user ===== \
  && groupadd --gid 1000 debian \
  && mkdir -p /home/debian \
  && useradd -c "debian user" --home-dir /home/debian --shell /bin/bash -g debian -m --uid 1000 debian && chown -R debian:debian /home/debian \
  && usermod -a -G root debian \
  && echo 'if [ "$BASH" ]; then if [ -f ~/.bashrc ]; then . ~/.bashrc; fi; fi' | tee -a /root/.bash_profile \
  && cp /root/.profile /home/debian/.profile \
  && cp /root/.bashrc /home/debian/.bashrc \
  && cp /root/.bash_profile /home/debian/.bash_profile \
  && chown -R 1000:1000 /home/debian \
  && echo "debian ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/debian \
  && chmod 0440 /etc/sudoers.d/debian

WORKDIR /home/debian
USER    debian
ENV HOME=/home/debian \
	SHELL=/bin/bash \
	USER=debian


COPY docker /
ENV PATH /usr/local/bin:${PATH}
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
