
FROM cirepo/bionic-cibase:latest






ARG IMAGE_ARG_APT_MIRROR

ARG IMAGE_ARG_ENCODING
ARG IMAGE_ARG_JAVA_OPTS
ARG IMAGE_ARG_LANGUAGE
ARG IMAGE_ARG_LOCALE
ARG IMAGE_ARG_REGION
ARG IMAGE_ARG_TZ_AREA
ARG IMAGE_ARG_TZ_ZONE

ARG IMAGE_ARG_USER
ARG IMAGE_ARG_VERSION





ENV HOME /home/${IMAGE_ARG_USER:-ubuntu}

ENV JAVA_OPTS -Duser.language=${IMAGE_ARG_LANGUAGE:-en} -Duser.region=${IMAGE_ARG_REGION:-US} -Dfile.encoding=${IMAGE_ARG_ENCODING:-UTF-8} -Duser.timezone=${IMAGE_ARG_TZ_AREA:-Etc}/${IMAGE_ARG_TZ_ZONE:-UTC} ${IMAGE_ARG_JAVA_OPTS}
ENV LANG ${IMAGE_ARG_LOCALE:-en_US}.${IMAGE_ARG_ENCODING:-UTF-8}
ENV LC_ALL ${IMAGE_ARG_LOCALE:-en_US}.${IMAGE_ARG_ENCODING:-UTF-8}


COPY --from=cirepo/locale:%IMAGE_ARG_LOCALE%.%IMAGE_ARG_ENCODING%_%IMAGE_ARG_TZ_AREA%.%IMAGE_ARG_TZ_ZONE%-bionic-archive /data/root /


RUN set -ex \
  && sudo curl --create-dirs -sSLo /usr/share/jenkins/swarm-client-${IMAGE_ARG_VERSION:-3.12}-jar-with-dependencies.jar \
    https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/${IMAGE_ARG_VERSION:-3.12}/swarm-client-${IMAGE_ARG_VERSION:-3.12}.jar \
  && sudo chmod 755 /usr/share/jenkins \
  && mkdir -p /home/${IMAGE_ARG_USER:-ubuntu}/.m2 \
  && mkdir -p /home/${IMAGE_ARG_USER:-ubuntu}/.ssh


VOLUME /home/${IMAGE_ARG_USER:-ubuntu}


COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
ENV PATH /usr/local/bin:${PATH}
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]


# install netstat to allow connection health check with
# netstat -tan | grep ESTABLISHED
RUN set -ex \
  && sudo sed -i "s/http:\/\/archive.ubuntu.com\/ubuntu\//http:\/\/${IMAGE_ARG_APT_MIRROR:-archive.ubuntu.com}\/ubuntu\//g" /etc/apt/sources.list \
  && sudo apt-get -y --allow-unauthenticated update \
  && sudo apt-get -y install net-tools iputils-ping \
  && sudo apt-get -q -y autoremove \
  && sudo apt-get -q -y clean && sudo rm -rf /var/lib/apt/lists/* && sudo rm -f /var/cache/apt/*.bin
